site_name: BMC TrueSight Pulse
theme: united
google_analytics: ['UA-47528703-5','auto']
pages:
- Home: index.md
- "Getting Started":
  - Installing: 'install.md'
  - Configuring: 'configuration.md'
- Reference:
  - Actions: 'reference/actions.md'
  - Alarms: 'reference/alarms.md'
  - Host Groups: 'reference/hostgroups.md'
  - Measurements: 'reference/measurements.md'
  - Metrics: 'reference/metrics.md'
  - Plugins: 'reference/plugins.md'
  - Relays: 'reference/relays.md'
  - Sources: 'reference/sources.md'

